package com.sqzn.tea.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sqzn.tea.Beans.CookBookDto;

import com.sqzn.tea.greendao.CookBookDtoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cookBookDtoDaoConfig;

    private final CookBookDtoDao cookBookDtoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cookBookDtoDaoConfig = daoConfigMap.get(CookBookDtoDao.class).clone();
        cookBookDtoDaoConfig.initIdentityScope(type);

        cookBookDtoDao = new CookBookDtoDao(cookBookDtoDaoConfig, this);

        registerDao(CookBookDto.class, cookBookDtoDao);
    }
    
    public void clear() {
        cookBookDtoDaoConfig.clearIdentityScope();
    }

    public CookBookDtoDao getCookBookDtoDao() {
        return cookBookDtoDao;
    }

}
