package com.sqzn.tea.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sqzn.tea.Beans.TeaDto;

import com.sqzn.tea.greendao.TeaDtoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig teaDtoDaoConfig;

    private final TeaDtoDao teaDtoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        teaDtoDaoConfig = daoConfigMap.get(TeaDtoDao.class).clone();
        teaDtoDaoConfig.initIdentityScope(type);

        teaDtoDao = new TeaDtoDao(teaDtoDaoConfig, this);

        registerDao(TeaDto.class, teaDtoDao);
    }
    
    public void clear() {
        teaDtoDaoConfig.clearIdentityScope();
    }

    public TeaDtoDao getTeaDtoDao() {
        return teaDtoDao;
    }

}
