package com.sqzn.tea.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sqzn.tea.Beans.FoodMaterielConvert;
import java.util.List;

import com.sqzn.tea.Beans.TeaDto;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEA_DTO".
*/
public class TeaDtoDao extends AbstractDao<TeaDto, Void> {

    public static final String TABLENAME = "TEA_DTO";

    /**
     * Properties of entity TeaDto.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property PictureImgUrl = new Property(0, String.class, "pictureImgUrl", false, "PICTURE_IMG_URL");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Introduction = new Property(2, String.class, "introduction", false, "INTRODUCTION");
        public final static Property FoodMaterielList = new Property(3, String.class, "foodMaterielList", false, "FOOD_MATERIEL_LIST");
    }

    private final FoodMaterielConvert foodMaterielListConverter = new FoodMaterielConvert();

    public TeaDtoDao(DaoConfig config) {
        super(config);
    }
    
    public TeaDtoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEA_DTO\" (" + //
                "\"PICTURE_IMG_URL\" TEXT," + // 0: pictureImgUrl
                "\"NAME\" TEXT," + // 1: name
                "\"INTRODUCTION\" TEXT," + // 2: introduction
                "\"FOOD_MATERIEL_LIST\" TEXT);"); // 3: foodMaterielList
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEA_DTO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TeaDto entity) {
        stmt.clearBindings();
 
        String pictureImgUrl = entity.getPictureImgUrl();
        if (pictureImgUrl != null) {
            stmt.bindString(1, pictureImgUrl);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String introduction = entity.getIntroduction();
        if (introduction != null) {
            stmt.bindString(3, introduction);
        }
 
        List foodMaterielList = entity.getFoodMaterielList();
        if (foodMaterielList != null) {
            stmt.bindString(4, foodMaterielListConverter.convertToDatabaseValue(foodMaterielList));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TeaDto entity) {
        stmt.clearBindings();
 
        String pictureImgUrl = entity.getPictureImgUrl();
        if (pictureImgUrl != null) {
            stmt.bindString(1, pictureImgUrl);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String introduction = entity.getIntroduction();
        if (introduction != null) {
            stmt.bindString(3, introduction);
        }
 
        List foodMaterielList = entity.getFoodMaterielList();
        if (foodMaterielList != null) {
            stmt.bindString(4, foodMaterielListConverter.convertToDatabaseValue(foodMaterielList));
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public TeaDto readEntity(Cursor cursor, int offset) {
        TeaDto entity = new TeaDto( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // pictureImgUrl
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // introduction
            cursor.isNull(offset + 3) ? null : foodMaterielListConverter.convertToEntityProperty(cursor.getString(offset + 3)) // foodMaterielList
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TeaDto entity, int offset) {
        entity.setPictureImgUrl(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIntroduction(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFoodMaterielList(cursor.isNull(offset + 3) ? null : foodMaterielListConverter.convertToEntityProperty(cursor.getString(offset + 3)));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(TeaDto entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(TeaDto entity) {
        return null;
    }

    @Override
    public boolean hasKey(TeaDto entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
